config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope module: :web do
    post 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth
    delete 'auth/logout', to: 'auth#logout'

    root 'bulletins#index'
    resources :bulletins, except: %i[destroy] do
      member do
        patch :archive
        patch :to_moderate
      end
    end

    get 'profile', to: 'profile#index', as: :profile

    namespace :admin do
      get '/', to: 'home#index'
      get 'bulletins', to: 'bulletins#index', as: :bulletins
      resources :bulletins, only: %i[] do
        member do
          patch :archive
          patch :publish
          patch :reject
        end
      end
      resources :categories, except: %i[show]
      resources :users, only: %i[index destroy edit update]
    end
  end

  match '/404', via: :all, to: 'errors#not_found'
  match '/422', via: :all, to: 'errors#unprocessable_entity'
  match '/500', via: :all, to: 'errors#server_error'
end

app/controllers/web/profile_controller.rb
# frozen_string_literal: true

module Web
  class ProfileController < ApplicationController
    def index
      authenticate_user!

      @q = Bulletin.by_owner(current_user).ransack(params[:q])
      @bulletins = @q.result.order(updated_at: :desc).page params[:page]
    end
  end
end

app/views/web/profile/_bulletin.html.slim
tr
  td
    = bulletin.title
  td
    = t("bulletin_states.#{bulletin.state}")
  td
    = time_ago_in_words bulletin.updated_at
  td
    = link_to t('.show'), bulletin_path(bulletin), class: 'me-2'
    =< link_to t('.edit'), edit_bulletin_path(bulletin), class: 'me-2'
    - if bulletin.may_to_moderate?
      =< link_to t('.to_moderate'), to_moderate_bulletin_path(bulletin), data: { turbo_method: :patch }, class: 'me-2'
    - if bulletin.may_archive?
      =< link_to t('.archive'), archive_bulletin_path(bulletin), data: { turbo_method: :patch, turbo_confirm: t('.confirm_archive') }, class: 'text-danger'

app/views/web/profile/_search_form.html.slim
- states = Bulletin.aasm.states.map(&:name)
- named_options = states.map { |state| [t("bulletin_states.#{state}"), state] }

= search_form_for @q, url: do |f|
  .row.my-2
    .col-6
      = f.input :title_cont, label: false, hint: t('.search_by_title'), hint_html: { class: 'text-muted' }
    .col-3
      = f.input :state_eq, as: :select, collection: named_options, label: false, hint: t('.select_by_state'), hint_html: { class: 'text-muted' }
    .col-3
      = f.submit t('.search'), class: 'btn btn-primary me-2 mb-2'
      = link_to t('.reset'), url, class: 'btn btn-outline-primary mb-2'

app/views/web/profile/index.html.slim
.mb-4
  h2
    = t('.my_bulletins')
  hr

= link_to t('.add_bulletin'), new_bulletin_path

== render partial: 'search_form', locals: { url: profile_url }

.row.mt-2
  table.table.table-borderless
    thead
      tr
        th
          = t('.title')
        th
          = t('.state')
        th
          = t('.publish_date')
        th
          = t('.actions')
    tbody

      == render partial: 'bulletin', collection: @bulletins

== paginate @bulletins, remote: true