config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope module: :web do
    post 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth
    delete 'auth/logout', to: 'auth#logout'

    root 'bulletins#index'
    resources :bulletins, except: %i[destroy] do
      member do
        patch :archive
        patch :to_moderate
      end
    end

    get 'profile', to: 'profile#index', as: :profile

    namespace :admin do
      get '/', to: 'home#index'
      get 'bulletins', to: 'bulletins#index', as: :bulletins
      resources :bulletins, only: %i[] do
        member do
          patch :archive
          patch :publish
          patch :reject
        end
      end
      resources :categories, except: %i[show]
      resources :users, only: %i[index destroy edit update]
    end
  end

  match '/404', via: :all, to: 'errors#not_found'
  match '/422', via: :all, to: 'errors#unprocessable_entity'
  match '/500', via: :all, to: 'errors#server_error'
end

app/views/layouts/shared/_flash.html.slim
- flash.each do |type, message|
  div[class=get_alert_class(type)]
    = message
    button.btn-close[aria-label="Close" data-bs-dismiss="alert" type="button"]

app/views/layouts/shared/_footer.html.slim
footer.bg-light.text-dark.mt-auto
  .py-2.text-center.fw-bold
    = t('.html')

app/views/layouts/shared/_head.html.slim
head
  title = t('.title')
  meta name="viewport" content="width=device-width,initial-scale=1"
  = csrf_meta_tags
  = csp_meta_tag
  = stylesheet_link_tag 'application', 'data-turbo-track': 'reload'
  = javascript_include_tag 'application', 'data-turbo-track': 'reload', defer: true
  = favicon_link_tag 'ruby32x32.png'

app/views/layouts/shared/_nav.html.slim
.container.mb-2
  .d-flex.flex-wrap.align-items-center.py-2.border-bottom
    .navbar.navbar-expand-md.navbar-light.me-auto
      = link_to t('.bulletin_board'), root_path, class: 'navbar-brand me-md-4'
      #navbarToggler.collapse.navbar-collapse
        ul.nav.nav-pills.flex-grow-1.navbar-nav.me-auto
          li.nav-item.me-2
            = link_to t('.main'), root_path, class: 'nav-link text-dark'
          - if signed_in?
            li.nav-item.me-2
              = link_to t('.my_bulletins'), profile_path, class: 'nav-link text-dark'
            li.nav-item.me-2
              = link_to t('.new_bulletin'), new_bulletin_path, class: 'nav-link text-dark'
    ul.nav.nav-pills
      - if signed_in?
        li.nav-item.me-2
          = link_to t('.admin_panel'), admin_path, class: "nav-link #{@current_user.admin? ? 'text-dark' : 'text-muted'}"
        li.nav-item.me-2
          = button_to t('.log_out'), auth_logout_path, method: :delete, class: 'nav-link text-dark'
      - else
        li.nav-item.me-2
          = button_to auth_request_path(:github), data: { turbo: 'false' }, class: 'nav-link text-dark' do
            span.bi.bi-github.me-2
            = t('.log_in')