config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope module: :web do
    post 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth
    delete 'auth/logout', to: 'auth#logout'

    root 'bulletins#index'
    resources :bulletins, except: %i[destroy] do
      member do
        patch :archive
        patch :to_moderate
      end
    end

    get 'profile', to: 'profile#index', as: :profile

    namespace :admin do
      get '/', to: 'home#index'
      get 'bulletins', to: 'bulletins#index', as: :bulletins
      resources :bulletins, only: %i[] do
        member do
          patch :archive
          patch :publish
          patch :reject
        end
      end
      resources :categories, except: %i[show]
      resources :users, only: %i[index destroy edit update]
    end
  end

  match '/404', via: :all, to: 'errors#not_found'
  match '/422', via: :all, to: 'errors#unprocessable_entity'
  match '/500', via: :all, to: 'errors#server_error'
end

app/controllers/web/admin/home_controller.rb
# frozen_string_literal: true

module Web
  module Admin
    class HomeController < Web::Admin::ApplicationController
      def index
        @bulletins = Bulletin.under_moderation.order(updated_at: :desc).page params[:page]
      end
    end
  end
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/views/web/admin/home/_bulletin.html.slim
tr
  td
    = link_to bulletin.title, bulletin_path(bulletin)
  td
    = time_ago_in_words bulletin.updated_at
  td
    - if bulletin.may_publish?
      = link_to t('.publish'), publish_admin_bulletin_path(bulletin), data: { turbo_method: :patch, turbo_confirm: t('.confirm_publish') }, class: 'me-1'
    - if bulletin.may_reject?
      =< link_to t('.reject'), reject_admin_bulletin_path(bulletin), data: { turbo_method: :patch, turbo_confirm: t('.confirm_reject') }, class: 'me-1'
    - if bulletin.may_archive?
      =< link_to t('.archive'), archive_admin_bulletin_path(bulletin), data: { turbo_method: :patch, turbo_confirm: t('.confirm_archive') }, class: 'text-danger'

app/views/web/admin/home/index.html.slim
h1.h2.mb-4
  = t('.ads_on_moderation')

.row.mt-2
  table.table.table-borderless
    thead
      tr
        th
          = t('.title')
        th
          = t('.publish_date')
        th
          = t('.actions')
    tbody

      == render partial: 'bulletin', collection: @bulletins

== paginate @bulletins, remote: true