config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope module: :web do
    post 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth
    delete 'auth/logout', to: 'auth#logout'

    root 'bulletins#index'
    resources :bulletins, except: %i[destroy] do
      member do
        patch :archive
        patch :to_moderate
      end
    end

    get 'profile', to: 'profile#index', as: :profile

    namespace :admin do
      get '/', to: 'home#index'
      get 'bulletins', to: 'bulletins#index', as: :bulletins
      resources :bulletins, only: %i[] do
        member do
          patch :archive
          patch :publish
          patch :reject
        end
      end
      resources :categories, except: %i[show]
      resources :users, only: %i[index destroy edit update]
    end
  end

  match '/404', via: :all, to: 'errors#not_found'
  match '/422', via: :all, to: 'errors#unprocessable_entity'
  match '/500', via: :all, to: 'errors#server_error'
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :bulletins, dependent: :restrict_with_error

  validates :name, presence: true
end

app/controllers/web/admin/categories_controller.rb
# frozen_string_literal: true

module Web
  module Admin
    class CategoriesController < Web::Admin::ApplicationController
      before_action :set_category, only: %i[edit update destroy]

      def index
        @categories = Category.page(params[:page])
        @category_bulletins_counts = Bulletin.group(:category).count
      end

      def new
        @category = Category.new
      end

      def edit; end

      def create
        @category = Category.new(category_params)

        if @category.save
          redirect_to admin_categories_url, notice: t('.success')
        else
          render :new, status: :unprocessable_entity
        end
      end

      def update
        if @category.update(category_params)
          redirect_to admin_categories_url, notice: t('.success')
        else
          render :edit, status: :unprocessable_entity
        end
      end

      def destroy
        if @category.destroy
          redirect_to admin_categories_url, status: :see_other, notice: t('.success')
        else
          redirect_to admin_categories_url, alert: t('.fail')
        end
      end

      private

      def set_category
        @category = Category.find(params[:id])
      end

      def category_params
        params.require(:category).permit(:name)
      end
    end
  end
end

app/views/web/admin/categories/_category.html.slim
tr
  td
    = category.name
  td
    = @category_bulletins_counts[category]
  td
    => link_to t('.edit'), edit_admin_category_path(category), class: 'me-1'
    =< link_to t('.delete'), admin_category_path(category), data: { turbo_method: :delete, turbo_confirm: t('.confirm_delete') },
    class: 'text-danger me-1'

app/views/web/admin/categories/_form.html.slim
h1.h2.mb-4
  = title

= simple_form_for(@category, url:) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :name, label: false, placeholder: t('.placeholder')

  .form-actions
    = f.button :submit, submit, class: 'btn btn-primary mt-2'

app/views/web/admin/categories/edit.html.slim
== render partial: 'form', category: @category,
   locals: { url: admin_category_url, title: t('.title'), submit: t('.submit') }

app/views/web/admin/categories/index.html.slim
h1.h2.mb-4
  = t('.title')
= link_to t('.add_category'), new_admin_category_path
.row.mt-2
  table.table.table-borderless
    thead
      tr
        th
          = t('.name')
        th
          = t('.category_ads_count')
        th
          = t('.actions')
    tbody
      == render @categories

== paginate @categories, remote: true

app/views/web/admin/categories/new.html.slim
== render partial: 'form', category: @category,
   locals: { url: admin_categories_url, title: t('.title'), submit: t('.submit') }